/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary.programme;

import adt.AdtInterface;
import static boundary.course.courseAddProgToCourse.programmeList;
import control.ProgrammeManagement;
import static control.ProgrammeManagement.programmeList;
import entity.Course;
import entity.Programme;
import entity.TutorialGroup;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import utility.insertData;
import static utility.insertData.tutorialList;

/**
 *
 * @author user
 */
public class programmeAddTutGrpToProgrammeGUI extends javax.swing.JFrame {

    public static AdtInterface<Programme> programmeList = insertData.programmeList;
    public static AdtInterface<Course> courseList = insertData.courseList;

    /**
     * Creates new form programmeAddTutGrpToProgrammeGUI
     */
    public programmeAddTutGrpToProgrammeGUI() {
        initComponents();
        setupProgrammeComboBox();
    }

    private void setupProgrammeComboBox() {
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();

        for (int i = 1; i <= tutorialList.getNumberOfEntries(); i++) {
            TutorialGroup tutorialGroup = tutorialList.getEntry(i);
            comboBoxModel.addElement(tutorialGroup.getGroupID());
        }
        Jcombo.setModel(comboBoxModel); // Set the model for the JComboBox

//        //Checking - Print the individual programme names
//        for (int i = 0; i < comboBoxModel.getSize(); i++) {
//            System.out.println("Programme Name: " + comboBoxModel.getElementAt(i));
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfProgrammeName = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        searchButton1 = new javax.swing.JButton();
        TitleLabel = new javax.swing.JLabel();
        jtfProgrammeCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ConfirmButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Jcombo = new javax.swing.JComboBox<>();
        AddTutorialGroupButton = new javax.swing.JButton();
        successMessageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtfProgrammeName.setEditable(false);
        jtfProgrammeName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtfProgrammeName.setToolTipText("");
        jtfProgrammeName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        searchButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchButton1.setText("SEARCH");
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });

        TitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        TitleLabel.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        TitleLabel.setText("ADD TUTORIAL GROUP into Programme");

        jtfProgrammeCode.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtfProgrammeCode.setToolTipText("");
        jtfProgrammeCode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jtfProgrammeCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfProgrammeCodeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("PROGRAMME NAME :");

        ConfirmButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ConfirmButton.setText("Confirm");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("PROGRAMME CODE :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("ADD TUTORIAL GROUP:");

        Jcombo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Jcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Jcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomboActionPerformed(evt);
            }
        });

        AddTutorialGroupButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        AddTutorialGroupButton.setText("Add Tutorial Group");
        AddTutorialGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTutorialGroupButtonActionPerformed(evt);
            }
        });

        successMessageLabel.setForeground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(TitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ConfirmButton)
                                .addGap(30, 30, 30)
                                .addComponent(backButton))
                            .addComponent(searchButton1)
                            .addComponent(successMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddTutorialGroupButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(Jcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(132, 132, 132))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jtfProgrammeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfProgrammeName, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(113, 113, 113)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel)
                .addGap(60, 60, 60)
                .addComponent(searchButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddTutorialGroupButton)
                .addGap(18, 18, 18)
                .addComponent(successMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConfirmButton)
                    .addComponent(backButton))
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(120, 120, 120)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jtfProgrammeCode, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jtfProgrammeName, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                    .addGap(225, 225, 225)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        setVisible(false);
        ProgrammeManagementMenu t = new ProgrammeManagementMenu();
        t.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
        String id = jtfProgrammeCode.getText().trim();

        // Create an instance of ProgrammeManagement to search for the program
        ProgrammeManagement search = new ProgrammeManagement();

        // Call the searchProgram method to find the program
        Programme programMatched = search.searchProgram(id);

        if (programMatched != null) {
            // If the program is found, update the text fields with its details
            jtfProgrammeName.setText(programMatched.getProgrammeName());
        } else {
            // If the program is not found, display an error message
            JOptionPane.showMessageDialog(
                    null, "Program with ID " + id + " was not found.", "Program Not Found", JOptionPane.INFORMATION_MESSAGE
            );

            // Clear the text fields
            jtfProgrammeName.setText("");
        }
    }//GEN-LAST:event_searchButton1ActionPerformed

    private void jtfProgrammeCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfProgrammeCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfProgrammeCodeActionPerformed

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
        String selectedTutorialGroup = Jcombo.getSelectedItem().toString(); // Get the selected tutorial group from the combo box
    String inputID = jtfProgrammeCode.getText();

    // Validate input
    if (inputID.isEmpty() || selectedTutorialGroup.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter both a Program Code and select a Tutorial Group.",
                "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Find the selected tutorial group's object
    TutorialGroup selectedTutorialGroupObject = null;
    for (int i = 1; i <= tutorialList.getNumberOfEntries(); i++) {
        TutorialGroup tutorialGroup = tutorialList.getEntry(i);
        if (tutorialGroup.getGroupID().equals(selectedTutorialGroup)) {
            selectedTutorialGroupObject = tutorialGroup;
            break; // Found the selected tutorial group, exit the loop
        }
    }

    if (selectedTutorialGroupObject == null) {
        JOptionPane.showMessageDialog(this, "Selected Tutorial Group not found.",
                "Tutorial Group Not Found", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Find the program and check if the tutorial group is already added
    for (int j = 1; j <= programmeList.getNumberOfEntries(); j++) {
        Programme program = programmeList.getEntry(j);
        if (program.getProgrammeCode().equals(inputID)) {
            // Check if the tutorial group is already added to this program
            if (!program.getTutorialGroups().contains(selectedTutorialGroupObject)) {
                // Tutorial group is not already added, so add it
                program.addTutorialGroup(selectedTutorialGroupObject);

                // Clear the input fields
                jtfProgrammeName.setText("");
                jtfProgrammeCode.setText("");

                // Display a success message
                successMessageLabel.setText("Program updated successfully!");
                successMessageLabel.setForeground(Color.GREEN); // Set the message color
            } else {
                // Tutorial group is already added, display an error message
                JOptionPane.showMessageDialog(this, "Tutorial Group " + selectedTutorialGroup + " is already added to this program.",
                        "Duplicate Tutorial Group", JOptionPane.ERROR_MESSAGE);
            }

            return; // Exit the loop after updating
        }
    }

    // If the program is not found, display an error message
    JOptionPane.showMessageDialog(this, "Program with Code " + inputID + " was not found.",
            "Program Not Found", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private void JcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomboActionPerformed

    }//GEN-LAST:event_JcomboActionPerformed

    private void AddTutorialGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTutorialGroupButtonActionPerformed
        // Show an input dialog to get tutorial group details
        String groupID = JOptionPane.showInputDialog(this, "Enter Group ID:");
        if (groupID != null) { // Check if the user clicked OK
            try {
                double groupAverageGrade = Double.parseDouble(
                        JOptionPane.showInputDialog(this, "Enter Group Average Grade:"));
                double groupAverageAttendance = Double.parseDouble(
                        JOptionPane.showInputDialog(this, "Enter Group Average Attendance:"));

                // Create a TutorialGroup object with the entered details
                TutorialGroup tutorialGroup = new TutorialGroup(groupID, groupAverageGrade, groupAverageAttendance);

                // Add the tutorial group to your data structure (ArrayList, etc.)
                tutorialList.add(tutorialGroup);

                // Display a success message (optional)
                JOptionPane.showMessageDialog(this, "Tutorial Group Added Successfully!");

                // Refresh the JComboBox
                Jcombo.revalidate();
                Jcombo.repaint();
            } catch (NumberFormatException e) {
                // Handle invalid number format
                JOptionPane.showMessageDialog(this, "Invalid input for grade or attendance. Please enter valid numbers.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_AddTutorialGroupButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(programmeAddTutGrpToProgrammeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(programmeAddTutGrpToProgrammeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(programmeAddTutGrpToProgrammeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(programmeAddTutGrpToProgrammeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new programmeAddTutGrpToProgrammeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTutorialGroupButton;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JComboBox<String> Jcombo;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtfProgrammeCode;
    private javax.swing.JTextField jtfProgrammeName;
    private javax.swing.JButton searchButton1;
    private javax.swing.JLabel successMessageLabel;
    // End of variables declaration//GEN-END:variables
}
