/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary.programme;

import adt.AdtInterface;
import control.ProgrammeManagement;
import entity.Course;
import entity.Programme;
import java.awt.Color;
import javax.swing.JOptionPane;
import utility.insertData;

/**
 *
 * @author user
 */
public class programmeUpdateGUI extends javax.swing.JFrame {

    public static AdtInterface<Course> courseList = insertData.courseList;

    /**
     * Creates new form programmeUpdate
     */
    public programmeUpdateGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchButton = new javax.swing.JButton();
        TitleLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jtfProgrammeName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ConfirmButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jtfProgrammeCode = new javax.swing.JTextField();
        successMessageLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        searchButton1 = new javax.swing.JButton();

        searchButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchButton.setText("SEARCH");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLabel.setBackground(new java.awt.Color(255, 255, 255));
        TitleLabel.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        TitleLabel.setText("Programme - UPDATE Programme");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("PROGRAMME CODE :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jtfProgrammeName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtfProgrammeName.setToolTipText("");
        jtfProgrammeName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("PROGRAMME NAME :");

        ConfirmButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ConfirmButton.setText("Update");
        ConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jtfProgrammeCode.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jtfProgrammeCode.setToolTipText("");
        jtfProgrammeCode.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jtfProgrammeCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfProgrammeCodeActionPerformed(evt);
            }
        });

        successMessageLabel.setForeground(new java.awt.Color(0, 204, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("PROGRAMME DESCRIPTION :");

        searchButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchButton1.setText("SEARCH");
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ConfirmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(backButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(successMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfProgrammeCode)
                                    .addComponent(jtfProgrammeName)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(TitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jtfProgrammeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jtfProgrammeName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(successMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConfirmButton)
                    .addComponent(backButton))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmButtonActionPerformed
 String newCode = jtfProgrammeCode.getText();
    String newName = jtfProgrammeName.getText();
    String newDesc = jTextArea1.getText();

    // Create an instance of ProgrammeManagement to search for the program
    ProgrammeManagement programManagement = new ProgrammeManagement();
    
    // Search for the program by code
    Programme programToUpdate = programManagement.searchProgram(newCode);

    if (programToUpdate != null) {
        // If the program is found, update its details
        programToUpdate.setProgrammeName(newName);
        programToUpdate.setProgrammeDescription(newDesc);

        // Clear the input fields
        jtfProgrammeName.setText("");
        jtfProgrammeCode.setText("");
        jTextArea1.setText("");

        // Display a success message
        successMessageLabel.setText("Programme updated successfully!");
        successMessageLabel.setForeground(Color.GREEN); // Set the message color
    } else {
        // If the program is not found, display an error message
        JOptionPane.showMessageDialog(
            null, "Program with Code " + newCode + " was not found.", "Program Not Found", JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_ConfirmButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        setVisible(false);
        ProgrammeManagementMenu t = new ProgrammeManagementMenu();
        t.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void jtfProgrammeCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfProgrammeCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfProgrammeCodeActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String id = jtfProgrammeCode.getText().trim();

        // Create an instance of ProgrammeManagement to search for the program
        ProgrammeManagement search = new ProgrammeManagement();

        // Call the searchProgram method to find the program
        Programme programMatched = search.searchProgram(id);

        if (programMatched != null) {
            // If the program is found, update the text fields with its details
            jtfProgrammeName.setText(programMatched.getProgrammeName());
            jTextArea1.setText(programMatched.getProgrammeDescription());
        } else {
            // If the program is not found, display an error message
            JOptionPane.showMessageDialog(
                    null, "Program with ID " + id + " was not found.", "Program Not Found", JOptionPane.INFORMATION_MESSAGE
            );

            // Clear the text fields
            jtfProgrammeName.setText("");
            jTextArea1.setText("");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
        String id = jtfProgrammeCode.getText().trim();

        // Create an instance of ProgrammeManagement to search for the program
        ProgrammeManagement search = new ProgrammeManagement();

        // Call the searchProgram method to find the program
        Programme programMatched = search.searchProgram(id);

        if (programMatched != null) {
            // If the program is found, update the text fields with its details
            jtfProgrammeName.setText(programMatched.getProgrammeName());
            jTextArea1.setText(programMatched.getProgrammeDescription());
        } else {
            // If the program is not found, display an error message
            JOptionPane.showMessageDialog(
                    null, "Program with ID " + id + " was not found.", "Program Not Found", JOptionPane.INFORMATION_MESSAGE
            );

            // Clear the text fields
            jtfProgrammeName.setText("");
            jTextArea1.setText("");
        }
    }//GEN-LAST:event_searchButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(programmeUpdateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(programmeUpdateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(programmeUpdateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(programmeUpdateGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new programmeUpdateGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jtfProgrammeCode;
    private javax.swing.JTextField jtfProgrammeName;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton searchButton1;
    private javax.swing.JLabel successMessageLabel;
    // End of variables declaration//GEN-END:variables
}
