/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boundary.programme;

import adt.AdtInterface;
import boundary.mainPage;
import control.ProgrammeManagement;
import entity.*;
import java.awt.BorderLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import utility.insertData;

/**
 *
 * @author: Er Qing Yap
 */
public class ProgrammeManagementMenu extends javax.swing.JFrame {

    public static AdtInterface<Programme> programmeList = insertData.programmeList;

    /**
     * Creates new form ProgrammeManagementMenu
     */
    public ProgrammeManagementMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        TitleLable = new javax.swing.JLabel();
        removeProgrammeButton = new javax.swing.JButton();
        addProgrammeButton = new javax.swing.JButton();
        updateProgrammeButton = new javax.swing.JButton();
        displayAllProgrammeButton = new javax.swing.JButton();
        searchTutorialByProgrammeButton = new javax.swing.JButton();
        searchProgrammeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        removeTutorialGroupButton = new javax.swing.JButton();
        programmeReportButton = new javax.swing.JButton();
        addTutorialGroupButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(1500, 800));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitleLable.setBackground(new java.awt.Color(255, 255, 255));
        TitleLable.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        TitleLable.setText("Programme Management System");
        jPanel5.add(TitleLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        removeProgrammeButton.setBackground(new java.awt.Color(204, 204, 204));
        removeProgrammeButton.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        removeProgrammeButton.setText("REMOVE");
        removeProgrammeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeProgrammeButtonActionPerformed(evt);
            }
        });
        jPanel5.add(removeProgrammeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 170, 380, 90));

        addProgrammeButton.setBackground(new java.awt.Color(204, 204, 204));
        addProgrammeButton.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        addProgrammeButton.setText("ADD");
        addProgrammeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProgrammeButtonActionPerformed(evt);
            }
        });
        jPanel5.add(addProgrammeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 380, 90));

        updateProgrammeButton.setBackground(new java.awt.Color(204, 204, 204));
        updateProgrammeButton.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        updateProgrammeButton.setText("UPDATE");
        updateProgrammeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProgrammeButtonActionPerformed(evt);
            }
        });
        jPanel5.add(updateProgrammeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 380, 90));

        displayAllProgrammeButton.setBackground(new java.awt.Color(204, 204, 204));
        displayAllProgrammeButton.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        displayAllProgrammeButton.setText("DISPLAY ALL");
        displayAllProgrammeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayAllProgrammeButtonActionPerformed(evt);
            }
        });
        jPanel5.add(displayAllProgrammeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 340, 380, 90));

        searchTutorialByProgrammeButton.setBackground(new java.awt.Color(204, 204, 204));
        searchTutorialByProgrammeButton.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        searchTutorialByProgrammeButton.setText("<html><div style='text-align:center;'>LIST<br>TUTORIAL GROUP</div></html>");
        searchTutorialByProgrammeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTutorialByProgrammeButtonActionPerformed(evt);
            }
        });
        jPanel5.add(searchTutorialByProgrammeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 490, 380, 200));

        searchProgrammeButton.setBackground(new java.awt.Color(204, 204, 204));
        searchProgrammeButton.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        searchProgrammeButton.setText("SEARCH");
        searchProgrammeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchProgrammeButtonActionPerformed(evt);
            }
        });
        jPanel5.add(searchProgrammeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 380, 90));

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel5.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 720, -1, -1));

        removeTutorialGroupButton.setBackground(new java.awt.Color(204, 204, 204));
        removeTutorialGroupButton.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        removeTutorialGroupButton.setText("<html><div style='text-align:center;'>REMOVE<br>TUTORIAL GROUP</div></html>");
        removeTutorialGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTutorialGroupButtonActionPerformed(evt);
            }
        });
        jPanel5.add(removeTutorialGroupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 380, 200));

        programmeReportButton.setBackground(new java.awt.Color(204, 204, 204));
        programmeReportButton.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        programmeReportButton.setText("REPORT");
        programmeReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programmeReportButtonActionPerformed(evt);
            }
        });
        jPanel5.add(programmeReportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 380, 90));

        addTutorialGroupButton.setBackground(new java.awt.Color(204, 204, 204));
        addTutorialGroupButton.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        addTutorialGroupButton.setText("<html><div style='text-align:center;'>ADD<br>TUTORIAL GROUP</div></html>");
        addTutorialGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTutorialGroupButtonActionPerformed(evt);
            }
        });
        jPanel5.add(addTutorialGroupButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 380, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeProgrammeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeProgrammeButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        programmeRemoveGUI t = new programmeRemoveGUI();
        t.setVisible(true);
    }//GEN-LAST:event_removeProgrammeButtonActionPerformed

    private void addProgrammeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProgrammeButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        programmeAddGUI t = new programmeAddGUI();
        t.setVisible(true);
    }//GEN-LAST:event_addProgrammeButtonActionPerformed

    private void updateProgrammeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProgrammeButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        programmeUpdateGUI t = new programmeUpdateGUI();
        t.setVisible(true);
    }//GEN-LAST:event_updateProgrammeButtonActionPerformed

    private void displayAllProgrammeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayAllProgrammeButtonActionPerformed
        // TODO add your handling code here:
        JTextArea textArea = new JTextArea(20, 40);
        textArea.setEditable(false);
        // Set the text of the JTextArea to the list of programs
        textArea.setText(ProgrammeManagement.getAllProgramme());
        textArea.setLineWrap(true); // Enable line wrapping
        textArea.setWrapStyleWord(true);

        // Create a JScrollPane to scroll through the programs if needed
        JScrollPane scrollPane = new JScrollPane(textArea);

        // Create a message to display above the programs
        String message = "List of All Programmes:";

        // Show the programs and the message in a JOptionPane
        JPanel panel = new JPanel(new BorderLayout());
        panel.add(new JLabel(message), BorderLayout.NORTH);
        panel.add(scrollPane, BorderLayout.CENTER);

        JOptionPane.showMessageDialog(null, panel, "Programme List", JOptionPane.PLAIN_MESSAGE);

        //JOptionPane.showMessageDialog(null, ProgrammeManagement.getAllProgramme());

    }//GEN-LAST:event_displayAllProgrammeButtonActionPerformed

    private void searchProgrammeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProgrammeButtonActionPerformed
        setVisible(false);
        programmeSearchGUI t = new programmeSearchGUI();
        t.setVisible(true);
    }//GEN-LAST:event_searchProgrammeButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        setVisible(false);
        mainPage t = new mainPage();
        t.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void removeTutorialGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTutorialGroupButtonActionPerformed
        setVisible(false);
        programmeRemoveTutGrpFromProgrammeGUI t = new programmeRemoveTutGrpFromProgrammeGUI();
        t.setVisible(true);
    }//GEN-LAST:event_removeTutorialGroupButtonActionPerformed

    private void addTutorialGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTutorialGroupButtonActionPerformed
        setVisible(false);
        programmeAddTutGrpToProgrammeGUI t = new programmeAddTutGrpToProgrammeGUI();
        t.setVisible(true);
    }//GEN-LAST:event_addTutorialGroupButtonActionPerformed

    private void programmeReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programmeReportButtonActionPerformed
        setVisible(false);
        programmeReportGUI t = new programmeReportGUI();
        t.setVisible(true);
    }//GEN-LAST:event_programmeReportButtonActionPerformed

    private void searchTutorialByProgrammeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTutorialByProgrammeButtonActionPerformed
        setVisible(false);
        programmeDisplayAllByProgramme t = new programmeDisplayAllByProgramme();
        t.setVisible(true);
    }//GEN-LAST:event_searchTutorialByProgrammeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgrammeManagementMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgrammeManagementMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgrammeManagementMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgrammeManagementMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgrammeManagementMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleLable;
    private javax.swing.JButton addProgrammeButton;
    private javax.swing.JButton addTutorialGroupButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton displayAllProgrammeButton;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton programmeReportButton;
    private javax.swing.JButton removeProgrammeButton;
    private javax.swing.JButton removeTutorialGroupButton;
    private javax.swing.JButton searchProgrammeButton;
    private javax.swing.JButton searchTutorialByProgrammeButton;
    private javax.swing.JButton updateProgrammeButton;
    // End of variables declaration//GEN-END:variables
}
